### ISSUE TITLE
Feature Request: property names should have their own class

### ISSUE THREAD

**Issue by KSXGitHub** [atom/language-json#38] opened 2015-12-17 12:12 UTC
Use class `property.name` instead of `string.quoted.double` for json property names

Like this one (expected):
![image](https://cloud.githubusercontent.com/assets/11488886/11869352/b9d4f2d8-a4f1-11e5-9860-12d11e93abfa.png)

But now in atom:
![image](https://cloud.githubusercontent.com/assets/11488886/11869385/f91e3e22-a4f1-11e5-9347-e00cefa24113.png)

**Comment by lee-dohm** [comment] 2015-12-17 17:41
This is a duplicate of #2. Please subscribe there for updates.

**Closed by lee-dohm** 2015-12-17 17:41 UTC
